### ISSUE TITLE
Missing - general properties/datas

### ISSUE THREAD

**Issue by shummo** [debpalash/nightwalker-qBittorrent-webUI#2]
Hi. I would love this theme, but unfortunatelly in the general info/ properties tab (general/trackers/peers/http sources/content), there is no datas. Full empty.

I know that there is no update since a year, but is there any way to get the infos there?
Thanks

**Comment by shummo** [comment]
It must be an error of my browser. I use Chrome, but there is no metadata. If i try with edge  or firefox. Then tey are there... :(

**Comment by debpalash** [comment]
I use [chromium](https://chromium.woolyss.com) from here and it works just fine for me. Try updating chrome(privacy nightmare tho) to latest, also make sure your addons are not interfereing.

**Comment by shummo** [comment]
Thanks for your fast help. 
my solution was to reset my chrome. Now matedatas there too. 
And alse thanks for the theme ;)
